[package]
name = "neit"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"
incremental = false
rpath = false
debug = false
overflow-checks = false
