[package]
name = "neit"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
lazy_static = "1.5.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
incremental = false