[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-static-pie",
    "-C", "target-feature=+crt-static",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",  # Use the static runtime
    "-C", "link-arg=-static",            # Link all libraries statically
    "-C", "link-arg=-nodefaultlibs",     # Don't link default libraries
]
